### ISSUE TITLE
コマンドの実装

### ISSUE THREAD

**Issue by book000** [jaoafa/jaotan.ts#49]
必要に応じて、コマンドごとにissue切り出ししてもOKです（・・・からConvert to issue）

```[tasklist]
### Tasks
- [ ] https://github.com/jaoafa/jaotan.ts/issues/71
- [ ] dice
- [x] getatama: api.tomacheese.comでバックエンドを立てて、かなあ…
- [ ] help: ドキュメントサイトへのリンク？
- [ ] javajaotan
- [ ] playing
- [ ] recid
- [x] search
- [x] searchimg
- [ ] toese
- [ ] tokanji: https://www.google.co.jp/ime/cgiapi.html
- [ ] typo
- [x] https://github.com/jaoafa/jaotan.ts/issues/157
- [x] https://github.com/jaoafa/jaotan.ts/issues/61
- [x] bassline
- [x] potato
- [x] https://github.com/jaoafa/jaotan.ts/issues/55
- [x] setnick
- [x] https://github.com/jaoafa/jaotan.ts/issues/56
- [x] tmttmt
- [x] toar
- [x] toarja
- [x] tochaos
- [x] toen
- [x] toenja
- [x] tohe
- [x] toheja
- [x] toja
- [x] tojaen
- [x] tokoja
- [x] torandja
- [x] tosw
- [x] toswja
- [x] tozh
- [x] tozhja
- [x] translate
- [ ] ~~chat~~
- [ ] ~~gentext~~
- [ ] ~~listening~~
- [ ] ~~mute~~
- [ ] ~~subaccount~~
- [ ] ~~test~~
- [ ] ~~towakati~~
- [ ] ~~toyomi~~
- [ ] ~~tweet~~
- [ ] ~~user~~
- [ ] ~~watching~~
- [ ] ~~kogo~~
- [ ] ~~setnickatama~~
```

**Comment by book000** [comment]
簡単（プログラミングまずやったことない人）

- tmttmt: 単一メッセージ返すだけ
- potato: 単一メッセージ返すだけ
- powa: 単一メッセージ返すだけ
- super: 単一メッセージ返すだけ
- akakese: 最初は引数なしでコマンド実行者に。その後引数のユーザへ
- recid: 最初は引数なし、出来たら引数あり
- alpha: 最初は引数なし。出来たら引数あり
- bassline: 最初は引数なし（ヒラタケへのみ）、出来たら引数あり

**Comment by Omuretsu** [comment]
`blmap``blookup`などは、Minecraftサーバを閉鎖したため移行しなくてもよいのではないでしょうか？

**Comment by book000** [comment]
蟹

**Comment by book000** [comment]
おおむねできたのでくろーず
