### ISSUE TITLE
イベント駆動の機能の実装

### ISSUE THREAD

**Issue by book000** [jaoafa/jaotan.ts#50]
```[tasklist]
### Tasks
- [ ] https://github.com/jaoafa/jaotan.ts/issues/808
- [x] MeetingVote
- [ ] https://github.com/jaoafa/jaotan.ts/issues/51
- [ ] https://github.com/jaoafa/jaotan.ts/issues/130
- [ ] https://github.com/jaoafa/jaotan.ts/issues/132
- [ ] https://github.com/jaoafa/jaotan.ts/issues/809
- [x] ServerJoin
- [x] ServerLeave
- [ ] ~~AntiEnEn~~
- [ ] ~~UserDedDB~~
- [ ] ~~WarnUsers~~
- [ ] ~~JoinWhichInvite~~
- [ ] ~~NeedSupport~~
```

- GameRoleは実装しない

**Comment by book000** [comment]
実装完了 + 切り出し済みのためクローズ
